### PR TITLE
test: use ISO 8601 date in test

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
Suggestion: Keep pushing your changes until this is MVP ready, then we can start having the usual PR workflow.

**Comment by ojeytonwilliams** [comment]
> Suggestion: Keep pushing your changes until this is MVP ready, then we can start having the usual PR workflow.

Sorry, I completely forgot that this would call the dev-team in for review. 

I was thinking that creating and merging my own PRs might help with visibility, but if that's too noisy I can go back to pushing them. What do you think?

**Comment by ShaunSHamilton** [comment]
> What do you think?

No worries 🙂 . I think it is faster for you to just push directly to the default branch. Nice commit messages would be a plus for visibility 📖 . Otherwise, I already do not have context for any PRs anyway.

**Comment by ojeytonwilliams** [comment]
Cool, thanks. I'll keep the noise down for now!

**Pull request merged**
